CREATE DATABASE CSE_3A_245

CREATE TABLE DEPOSIT(
	ACTNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2),
	ADATE DATETIME
);

INSERT INTO DEPOSIT VALUES (101,'ANIL','VRCE',1000,'1995-3-1')
INSERT INTO DEPOSIT (ACTNO, CNAME, BNAME, AMOUNT, ADATE) VALUES (102,'SUNIL','AJNI',5000,'1996-1-4')
INSERT INTO DEPOSIT VALUES (103,'MEHUL','KAROLBAGH',3500,'1995-12-17')
INSERT INTO DEPOSIT (ACTNO, CNAME, BNAME, AMOUNT, ADATE) VALUES
	(104,'MADHURI','CHANDI',1200,'1995-12-17'),
	(105,'PRAMOD','M.G. ROAD',3000,'1996-3-27'),
	(106,'SANDIP','ANDHERI',2000,'1996-3-31'),
	(107,'SHIVANI','VIHAR',1000,'1995-9-5'),
	(108,'KRANTI','NEHRU PLACE',5000,'1995-7-2'),
	(109,'MINU','POWAI',7000,'1995-8-10')

SELECT * FROM DEPOSIT

--TABLE2
CREATE TABLE BRANCH(
	BNAME VARCHAR(50),
	CITY VARCHAR(50)
)

INSERT INTO BRANCH VALUES ('VRCE','NAGPUR')
INSERT INTO BRANCH VALUES ('AJNI','NAGPUR'),('KAROLBAGH','DELHI')
INSERT INTO BRANCH (BNAME,CITY) VALUES ('CHANDI','DELHI'),
	('DHARAMPETH','NAGPUR'),
	('M.G. ROAD','BANGLORE'),
	('ANDHERI','BOMBAY'),
	('VIHAR','BOMBAY'),
	('NEHRU PLACE','DELHI'),
	('POWAI','BOMBAY')

SELECT * FROM BRANCH

--TABLE3
CREATE TABLE CUSTOMERS(
	CNAME VARCHAR(50), CITY VARCHAR(50)
)
INSERT INTO CUSTOMERS VALUES ('ANIL','CALCUTTA')
INSERT INTO CUSTOMERS VALUES ('SUNIL','DELHI')
INSERT INTO CUSTOMERS VALUES ('MEHUL','BARODA')
INSERT INTO CUSTOMERS VALUES ('MANDAR','PATNA')
INSERT INTO CUSTOMERS VALUES ('MADHURI','NAGPUR')
INSERT INTO CUSTOMERS VALUES ('SANDIP','NAGPUR')
INSERT INTO CUSTOMERS VALUES ('SANDIP','SUART')
INSERT INTO CUSTOMERS VALUES ('SHIVANI','BOMBAY')
INSERT INTO CUSTOMERS VALUES ('KRANTI','BOMBAY')
INSERT INTO CUSTOMERS VALUES ('NAREN','BOMABAY')

SELECT * FROM CUSTOMERS

CREATE TABLE BORROW(
	LOANNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2)
)

INSERT INTO BORROW VALUES (201,'ANIL','VRCE',1000),
	(206,'MEHUL','AJNI',5000),
	(311,'SUNIL','DHARAMPETH',3000),
	(321,'MADHURI','ANDHERI',2000),
	(375,'PRAMOD','VIRAR',8000),
	(481,'KRANTI','NEHRU PALACE',3000)

SELECT * FROM BORROW